app_name: goin-test-app
http:
  addr: :8081
database:
  host: localhost
  port: 3306
  user: root
  password: password
  dbname: goin_test
logger:
  level: info
  output: [console]
jwt:
  secret: your-secret-key # JWT 密钥
  access_token_exp: 15m # Access Token 过期时间
  refresh_token_exp: 168h # Refresh Token 过期时间
redis:
  addr: localhost:6379
  password: ""
  db: 0
